[package]
name = "binius_core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
assert_matches.workspace = true
auto_impl.workspace = true
binius_field = { path = "../field" }
binius_hash = { path = "../hash" }
binius_ntt = { path = "../ntt" }
binius_utils = { path = "../utils" }
bytemuck = { workspace = true, features = ["extern_crate_alloc"] }
derive_more.workspace = true
either.workspace = true
getset.workspace = true
itertools.workspace = true
p3-challenger.workspace = true
p3-matrix.workspace = true
p3-symmetric.workspace = true
p3-util.workspace = true
rand.workspace = true
rayon.workspace = true
thiserror.workspace = true
thread_local.workspace = true
tracing.workspace = true
transpose.workspace = true

[dev-dependencies]
anyhow.workspace = true
criterion.workspace = true
proptest.workspace = true
tiny-keccak.workspace = true
tracing-profile.workspace = true
tracing-subscriber.workspace = true

[lib]
bench = false

[[bench]]
name = "sumcheck"
harness = false

[[bench]]
name = "multilinear_query"
harness = false

[[bench]]
name = "util"
harness = false

[[bench]]
name = "zerocheck"
harness = false

[[bench]]
name = "gkr_prodcheck"
harness = false

[features]
debug_validate_sumcheck = []
bail_panic = []
